<%
  @path = "#{RUBBER_ROOT}/config/amazon_s3.yml"
%>

<%= RUBBER_ENV %>:
  bucket_name: trek.io
  access_key_id: AKIAI3R3BQ2V7SZ3Z62Q
  secret_access_key: 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
  distribution_domain: assets.escapist.me
