--- 
javascripts: 
    
- preload: 
    - jquery-1.5.1.min
    - jquery.inputhints.min
    - application
    - jquery.tools.min
    - jquery-ui-1.8.13.custom.min
    - autoresize.jquery.min
    - jquery.numeric.pack
    - jquery.ptTimeSelect
    - jquery.lightbox-0.5.pack
    - jquery.ellipsis
    - history
    - history.adapter.jquery
    - json2
    - amplify.store.js
        
- postload:
    - jquery.url.min
    - jquery.maskedinput-1.2.2.min
    - jquery.autocomplete.pack
    - sanitize
    - jquery-impromptu.3.1.min
   
stylesheets: 
- base: 
  - theme
  - impromptu
  - jquery-ui-1.8.4.custom
  - jquery.lightbox-0.5
  


