--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: stomp.io
  external_host: ec2-50-17-57-178.compute-1.amazonaws.com
  external_ip: 50.17.57.178
  instance_id: i-a75c08cb
  internal_host: ip-10-203-13-80.ec2.internal
  internal_ip: 10.203.13.80
  name: web01
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  root_device_type: ebs
  security_groups: 
  - stomp_production_default
  - stomp_production_web
  - stomp_production_web01
  - stomp_production_haproxy
  - stomp_production_app
  - stomp_production_passenger
  - stomp_production_apache
  zone: us-east-1c
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: stomp.io
  external_host: ec2-50-17-77-119.compute-1.amazonaws.com
  external_ip: 50.17.77.119
  instance_id: i-cd5f0ba1
  internal_host: ip-10-80-27-13.ec2.internal
  internal_ip: 10.80.27.13
  name: db01
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - stomp_production_default
  - stomp_production_db01
  - stomp_production_db
  - stomp_production_mysql_master
  zone: us-east-1c
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: stomp.io
  external_host: ec2-50-17-41-214.compute-1.amazonaws.com
  external_ip: 50.17.41.214
  instance_id: i-435a072f
  internal_host: ip-10-116-141-46.ec2.internal
  internal_ip: 10.116.141.46
  name: db02
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_slave
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: sphinx
    options: {}

  root_device_type: ebs
  security_groups: 
  - stomp_production_default
  - stomp_production_db02
  - stomp_production_db
  - stomp_production_mysql_slave
  - stomp_production_sphinx
  zone: us-east-1c
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: stomp.io
  external_host: ec2-204-236-240-184.compute-1.amazonaws.com
  external_ip: 204.236.240.184
  instance_id: i-e2c8038d
  internal_host: ip-10-243-35-111.ec2.internal
  internal_ip: 10.243.35.111
  name: web02
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  root_device_type: ebs
  security_groups: 
  - stomp_production_default
  - stomp_production_web
  - stomp_production_web02
  - stomp_production_haproxy
  - stomp_production_app
  - stomp_production_passenger
  - stomp_production_apache
  zone: us-east-1c
- volumes: {}

  static_ips: {}

