--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: stomp.io
  external_host: ec2-50-16-53-172.compute-1.amazonaws.com
  external_ip: 50.16.53.172
  instance_id: i-9b6a26f7
  internal_host: ip-10-202-194-20.ec2.internal
  internal_ip: 10.202.194.20
  name: nap
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: sphinx
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: ebs
  security_groups: 
  - stomp_nap_default
  - stomp_nap_web
  - stomp_nap_nap
  - stomp_nap_haproxy
  - stomp_nap_app
  - stomp_nap_passenger
  - stomp_nap_apache
  - stomp_nap_sphinx
  - stomp_nap_db
  - stomp_nap_mysql_master
  zone: us-east-1c
- volumes: {}

  static_ips: {}

